name: test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install npm dependencies
        run: |
          npm install --legacy-peer-deps
        id: install-dependencies

      - name: Clone EVM Tableland Repository
        run: |
          git clone https://github.com/tablelandnetwork/evm-tableland.git
          cd evm-tableland
        id: clone

      - name: Install tableland dependencies
        run: |
          cd evm-tableland
          npm install
        id: install-tableland-dependencies

      - name: Run Local Chain with Anvil
        run: |
          anvil &
        id: local-chain

      - name: Run Hardhat Deployment Script
        run: |
          cd evm-tableland
          npx hardhat run scripts/deploy.ts --network localhost
        id: deploy

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --via-ir --optimize --optimizer-runs 200 --no-yul
        id: build

      - name: Run Forge tests
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          forge test --via-ir --fork-url http://localhost:8545 -vvvv
        id: test
