name: test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Local Chain with Anvil
        run: |
          anvil &
        id: local-chain

      - name: Clone JuiceBox Core Repository
        run: |
          git clone https://github.com/Bananapus/nana-core
          cd nana-core
        id: clone-juicebox

      - name: Install JuiceBox dependencies
        run: |
          cd nana-core
          npm ci && forge install
        id: install-juicebox-dependencies

      - name: Run JuiceBox Deployment Script
        run: |
          cd nana-core
          awk '/^\[rpc_endpoints\]$/ {print; print "local = \"http://127.0.0.1:8545\""; next} 1' foundry.toml > temp && mv temp foundry.toml # add local chain to foundry.toml
          PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" npx sphinx deploy script/Deploy.s.sol --network local --confirm # private key is the default anvil key, not a secret
        id: deploy-juicebox

      - name: Clone EVM Tableland Repository
        run: |
          git clone https://github.com/tablelandnetwork/evm-tableland.git
          cd evm-tableland
        id: clone

      - name: Install tableland dependencies
        run: |
          cd evm-tableland
          npm install
        id: install-tableland-dependencies

      - name: Run Hardhat Deployment Script
        run: |
          cd evm-tableland
          npx hardhat run scripts/deploy.ts --network localhost
        id: deploy-hardhat

      - name: Install npm dependencies
        run: |
          npm install --legacy-peer-deps
        id: install-dependencies

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --via-ir --optimize --optimizer-runs 200
        id: build

      - name: Run Forge tests
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          forge test --via-ir --optimize --optimizer-runs 200 --fork-url http://localhost:8545 -vvvv
        id: test
